openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: "REST API for a simple managment of tasks and authentication. Inspired by ChatGPT but redone by myself afterwards"
  version: 1.1.0

servers:
  - url: http://localhost:3000
tags:
  - name: authentication
    description: Everything about authentication
  - name: tasks
    description: Everything about tasks

paths:
  /login:
    post:
      summary: Login
      tags: 
      - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        400:
          description: Bad Request - Invalid email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        401:
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /verify:
    get:
      summary: Check login status
      tags: 
      - authentication
      responses:
        200:
          description: Currently logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        401:
          description: Not logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /logout:
    delete:
      summary: Logout
      tags: 
      - authentication
      responses:
        204:
          description: Logged out successfully
        401:
          description: Not logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /tasks:
    get:
      summary: Get all tasks
      tags: 
      - tasks
      responses:
        200:
          description: Retrieved tasks successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
      - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        201:
          description: Created task successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        406:
          description: Title is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /tasks/{id}:
    get:
      summary: Get a task by Id
      tags:
      - tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Retrieved task successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        404:
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Update a task by Id
      tags:
      - tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                finishedDate:
                  type: string
                  format: date
              required:
                - title
      responses:
        200:
          description: Updated task successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        404:
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        406:
          description: Title is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: Delete a task by Id
      tags:
      - tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Deleted task successfully
        404:
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        creationDate:
          type: string
          format: date
        finishedDate:
          type: string
          format: date
        creator:
          type: string
      required:
        - id
        - title
        - creationDate
        - creator
